#!/usr/bin/env bash

set -e

PARENT_PATH=$(dirname $(
  cd $(dirname $0)
  pwd -P
))

pushd $PARENT_PATH

## now loop through the above array
for current in "swap" "types" "trade"; do
  mkdir -p ./generated/go/$current
  protoc \
    --go-grpc_out=paths=source_relative:./generated/go/$current \
    --go_out=paths=source_relative:./generated/go/$current \
    $current.proto
done

popd
