#!/usr/bin/env bash

set -ex

PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH

PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts"
GRPC_TOOLS_NODE_PROTOC_PLUGIN="./node_modules/.bin/grpc_tools_node_protoc_plugin"
GRPC_TOOLS_NODE_PROTOC="./node_modules/.bin/grpc_tools_node_protoc"

# loop over all the available proto files and compile them into respective dir
# JavaScript code generating
${GRPC_TOOLS_NODE_PROTOC} \
  --js_out=import_style=commonjs,binary:./js \
  --grpc_out=./js \
  --plugin=protoc-gen-grpc="${GRPC_TOOLS_NODE_PROTOC_PLUGIN}" \
  trade.proto operator.proto

${GRPC_TOOLS_NODE_PROTOC} \
  --plugin=protoc-gen-ts="${PROTOC_GEN_TS_PATH}" \
  --ts_out=./js \
  *.proto

popd
