#!/usr/bin/env bash
set -ex
PARENT_PATH=$(dirname $(cd $(dirname $0); pwd -P))

pushd $PARENT_PATH

mkdir -p js
protoc  \
  --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
  --js_out=import_style=commonjs,binary:./js  \
  --ts_out=./js  \
  *.proto

popd
