#!/usr/bin/env bash

set -e

PARENT_PATH=$(dirname $(
  cd $(dirname $0)
  pwd -P
))

pushd $PARENT_PATH

mkdir -p ./generated/java
protoc \
  --java-grpc_out=./generated/java \
  --java_out=./generated/java \
  *.proto

mkdir -p ./generated/java-lite
protoc \
  --java-grpc_out=lite:./generated/java-lite \
  --java_out=lite:./generated/java-lite \
  *.proto

popd
