#!/usr/bin/env bash

set -e

PARENT_PATH=$(dirname $(
  cd $(dirname $0)
  pwd -P
))

pushd $PARENT_PATH

PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts"
GRPC_TOOLS_NODE_PROTOC_PLUGIN="./node_modules/.bin/grpc_tools_node_protoc_plugin"
GRPC_TOOLS_NODE_PROTOC="./node_modules/.bin/grpc_tools_node_protoc"
GRPC_WEB_PLUGIN="./node_modules/.bin/protoc-gen-grpc-web"

# loop over all the available proto files and compile them into respective dir
# JavaScript code generating
${GRPC_TOOLS_NODE_PROTOC} \
  --js_out=import_style=commonjs,binary:./generated/js \
  --grpc_out=grpc_js:./generated/js \
  trade.proto operator.proto wallet.proto types.proto

${GRPC_TOOLS_NODE_PROTOC} \
  --js_out=import_style=commonjs,binary:./generated/js \
  --grpc-web_out=import_style=typescript,mode=grpcwebtext:./generated/js \
  --plugin=protoc-gen-grpc-web=${GRPC_WEB_PLUGIN} \
  *.proto

${GRPC_TOOLS_NODE_PROTOC} \
  --js_out=import_style=commonjs,binary:./generated/js \
  --plugin=protoc-gen-ts="${PROTOC_GEN_TS_PATH}" \
  --ts_out=grpc_js:./generated/js \
  *.proto


popd
