name: Compile protobuf stubs

on:
  push:
    branches: [v1]

jobs:
  # This workflow contains a single job called "compile"
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Install dependencies
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: v1

      - name: Setup build.buf
        uses: bufbuild/buf-setup-action@v0.6.0

      - name: Generate stubs
        uses: make proto

      - name: Commit generated stubs
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git add -A
          git commit -m "Automated: Update protobuf stubs"
          git push origin v1
