name: Lint & Push protos to buf.build registry

on:
  push:
    branches: [v1]

jobs:
  # This workflow contains a single job called "compile"
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Install dependencies
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: v1

      - name: Setup build.buf
        uses: bufbuild/buf-setup-action@v1.1.0
        with:
          version: 1.1.0

      - name: Lint protos
        run: make lint

      - uses: bufbuild/buf-push-action@v1        
        with:          
          input: api-spec/protobuf
          buf_token: ${{ secrets.BUF_TOKEN }}
